services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: kdi-kendarikota-app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
      - "5173:5173"
    # depends_on:
    #   - db
    networks:
      - shared-mysql-net

  web:
    image: nginx:alpine
    container_name: kdi-kendarikota-nginx
    ports:
      - "8002:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - shared-mysql-net

networks:
  shared-mysql-net:
    external: true
