services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: kdi-kendarikota-app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - db

  web:
    image: nginx:alpine
    container_name: kdi-kendarikota-nginx
    ports:
      - "8002:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: kdi-kendarikota-mysql
    restart: always
    environment:
      MYSQL_DATABASE: db_kendarikota
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: kendarikota
      MYSQL_PASSWORD: kendarikota123
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3308:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: kdi-kendarikota-phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8082:80"
    depends_on:
      - db

volumes:
  dbdata:
